<form action="addCategory.php" method="post" enctype="multipart/form-data">
    <fieldset>
        <legend>Ajout d'une catégorie</legend>
        
            <?php if(!is_null($id)):?>
              <input type="hidden" value="<?=$id?>" name="id">
            <?php endif;?>
            <div class="form-group">
              <label for="exampleInputEmail1">Titre :</label>
              <input type="text" class="form-control" id="titre" name="titre" value="<?=$titleCategory?>">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Catégorie parent :</label>
              <select class="form-control" id="categorie" name="categorie">
                  <option value="">Aucune</option>
                  <?php foreach($categories as $categorie):?>
                    <option value="<?=$categorie['c_id']?>" <?php if($catParent == $categorie['c_id']):?>selected<?php endif;?>><?=$categorie['c_title']?></option>
                  <?php endforeach;?>
              </select>
            </div>
            <button type="submit" class="btn btn-primary">Ajouter</button>
    </fieldset>
</form>