<form action="addUser.php" method="post" enctype="multipart/form-data">
    <fieldset>
        <legend>Ajout d'un utilisateur</legend>
        
            <?php if(!is_null($id)):?>
              <input type="hidden" value="<?=$id?>" name="id">
            <?php endif;?>
            <div class="form-group">
              <label for="exampleInputEmail1">Prénom :</label>
              <input type="text" class="form-control" id="prenom" name="prenom">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Nom :</label>
              <input type="text" class="form-control" id="nom" name="nom">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Adresse E-mail :</label>
              <input type="email" class="form-control" id="mail" name="mail">
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Mot de passe :</label>
              <input type="password" class="form-control" id="password" name="password">
            </div>
            <div class="form-group">
              <label for="exampleSelect1">Rôle :</label>
              <select class="form-control" id="role" name="role">
                <option></option>
              </select>
            </div>
            <button type="submit" class="btn btn-primary">Ajouter</button>
    </fieldset>
</form>