<form action="addArticle.php" method="post" enctype="multipart/form-data">
  <fieldset>
    <legend>Modifier un article:</legend>
    <div class="form-group">
      <label class="col-form-label" for="inputDefault">Titre :</label>
      <input type="text" class="form-control" name="titre" id="titre" value="<?=$titre?>">
    </div>
    <div class="form-group">
      <label for="exampleSelect1">Catégories</label>
      <select class="form-control" name="categorie" id="categorie">
        <?php foreach($categories as $categorie):?>
          <option value="<?=$categorie['c_id']?>" <?php if($categorieArticle == $categorie['c_id']):?>selected<?php endif;?>><?=$categorie['c_title']?></option>
        <?php endforeach;?>
      </select>
    </div>
    <div class="form-group">
      <label for="exampleTextarea">Contenu</label>
      <textarea class="form-control" name="contenu" id="contenu" rows="3"><?=$contenu?></textarea>
    </div>
    <div class="form-group">
      <label for="exampleInputFile">Ajouter une image</label>
      <input type="file" class="form-control-file" name="image" id="image" aria-describedby="fileHelp">
      <?php if($picture != '' &&  $picture != null):?>
        <input type="hidden" name="oldPicture" value="<?=$picture?>">
      <?php endif;?>
      <?php if($pictureDisplay):?>
        <img src="<?=UPLOADS_URL.'articles/'.$picture?>" width="200">
      <?php endif;?>
    </div>
    <div class="form-group">
      <label class="col-form-label" for="inputDefault">Auteur :</label>
      <input type="text" class="form-control" name="auteur" id="auteur" value="<?=$auteur?>">
    </div>
    <div class="form-group">
      <label class="col-form-label" for="date">Date et heure de publication</label>
      <input type="date" class="form-control"  id="date" name="date" value="<?=$datePubli->format('Y-m-d')?>">
      <input type="time" class="form-control"  id="heure" name="heure" value="<?=$datePubli->format('H:m')?>">
    </div>
    
    
    </fieldset>
    <button type="submit" class="btn btn-primary">Modifier</button>
  </fieldset>
</form>