<form action="editCategory.php" method="post" enctype="multipart/form-data">
    <fieldset>
        <legend>Modification d'une catégorie</legend>
            
            <?php if(isset($errorForm) && count($errorForm)>0):?>
              <div class="alert alert-danger" role="alert">
                <ul>
                  <?php foreach($errorForm as $error):?>
                    <li class="erreur"><?=$error;?></li>
                  <?php endforeach;?>
                </ul>  
              </div>
            <?php endif;?>
            
            <?php if(!is_null($id)):?>
              <input type="hidden" value="<?=$id?>" name="id">
            <?php endif;?>
            <div class="form-group">
              <label for="exampleInputEmail1">Titre :</label>
              <input type="text" class="form-control" id="titre" name="titre" value="<?=$titleCategory?>">
            </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Catégorie parent :</label>
              <select class="form-control" id="categorie" name="categorie">
                  <option value="">Aucune</option>
                  <?php foreach($categories as $categorie):?>
                    <option value="<?=$categorie['c_id']?>" <?php if($catParent == $categorie['c_id']):?>selected<?php endif;?>><?=$categorie['c_title']?></option>
                  <?php endforeach;?>
              </select>
            </div>
            <button type="submit" class="btn btn-primary">Modifier</button>
    </fieldset>
</form>