<a href="addArticle.php"><i class="fas fa-plus"></i> Ajouter un article</a>
<table class="table table-hover">
    <thead>
        <tr>
          <th scope="col">Titre</th>
          <th scope="col">Catégories</th>
          <th scope="col">Contenu</th>
          <th scope="col">Image</th>
          <th scope="col">Auteur</th>
          <th scope="col">Date de Publication</th>
          <th scope="col">Actions</th>
        </tr>
    </thead>
  
    <tbody>
        <?php foreach($results as $result):?>
            <tr class="table-secondary">
                <th scope="row"><?=$result['a_title']?></th>
                <td><?=$result['a_categorie']?></td>
                <td><?=$result['a_content']?></td>
                <td><img width="70" src="<?=UPLOADS_URL.'articles/'.$result['a_picture']?>"></td>
                <td><?=$result['a_author']?></td>
                <td><?=(new DateTime($result['a_date_published']))->format('d/m/y H:i:s')?></td>
                <td><a href="delArticle.php?id=<?=$result['a_id']?>"><i class="fas fa-trash-alt"></i></a> <a href="editArticle.php?id=<?=$result['a_id']?>"><i class="fas fa-edit"></i></a></td>
            </tr>
        <?php endforeach;?>    
    </tbody>    
 </table>