<a href="addCategory.php"><i class="fas fa-plus"></i> Ajouter une catégorie</a>
<table class="table table-hover">
    <thead>
        <tr>
          <th scope="col">Nom</th>
          <th scope="col">Catégorie parent</th>
          <th scope="col">Actions</th>          
        </tr>
    </thead>
  
    <tbody>
        <?php foreach($categories as $categorie):?>
            <tr class="table-secondary">
                <th scope="row"><?=$categorie['c_title']?></th>
                <td><?=$categorie['parent']?></td>
                <td><a href="delCategory.php?id=<?=$categorie['c_id']?>"><i class="fas fa-trash-alt"></i></a> <a href="editCategory.php?id=<?=$categorie['c_id']?>"><i class="fas fa-edit"></i></a></td>
            </tr>
        <?php endforeach;?>    
    </tbody>    
 </table>