<a href="addUser.php"><i class="fas fa-plus"></i>Nouvel utilisateur </a>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">Prénom</th>
      <th scope="col">E-mail</th>
      <th scope="col">Rôle</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($users as $user):?>
    <tr class="table-info">
      <td><?=$user['u_lastname']?></td>
      <td><?=$user['u_firstname']?></td>
      <td><?=$user['u_email']?></td>
      <td></td>
      <td><a href="delUser.php?id=<?=$user['u_id']?>"><i class="fas fa-trash-alt"></i></a> <a href="#"><i class="fas fa-edit"></i></a></td>
    </tr>
    <?php endforeach;?>
  </tbody>
</table>  