<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V16</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="css/main.css">
	<link rel="stylesheet" type="text/css" href="css/util.css">

</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url('images/bg-01.jpg');">
			<div class="wrap-login100 p-t-30 p-b-50">
				<span class="login100-form-title p-b-41">Bienvenue </span>
				<form method="POST" action="login.php" class="login100-form validate-form p-b-33 p-t-5">
				
					<?php if(isset($errorForm) && count($errorForm)>0):?>
				        <div class="alert alert-danger" role="alert">
				            <ul>
				                <?php foreach($errorForm as $error):?>
				                	<li class="erreur"><?=$error;?></li>
				                <?php endforeach;?>
				            </ul>  
				        </div>
				    <?php endif;?>
				   
					<div class="wrap-input100 validate-input" data-validate = "Enter username">
						<input id="email" class="input100" type="text" name="email" placeholder="Identifiant">
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input id="motdepasse" class="input100" type="password" name="motdepasse" placeholder="Mot de passe">
					</div>

					<div class="container-login100-form-btn m-t-32">
						<button class="login100-form-btn">Login</button>
					</div>

				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>